### ISSUE TITLE
"Something went wrong... 💩 Unexpected end of JSON input"

### ISSUE THREAD

**Issue by Marc13Bautista** [a-sync/arma3pregen#1]
![image](https://github.com/a-sync/arma3pregen/assets/35089747/4ec84464-72e1-4250-a235-fd5b3d807d46)

Before my preset files I made for my mod collection worked fine. But suddenly a few stopped working for some reason? Maybe after an update a week ago. 

https://arma3pregen.devs.space/?MSP_VANILLA=2923506574,2415922767,!639600,1261751004*
https://arma3pregen.devs.space/?MSPL_VANILLA=2977613979,2976826815,!639600,1261751004*
https://arma3pregen.devs.space/?MSP_WW2=2923494722,2415922767,!1175380,1261751004*

**Comment by a-sync** [comment]
hey @Marc13Bautista,
thanks for bringig this to my attention!  

i switched to the key protected steam API about a week ago after i noticed a few workshop files were not found on the open API endpoint. 😔  
unfortunately there was a bug when using the protected API with large number of workshop items 😨... but 
should be fixed now 😬
make sure to hit CTRL+F5 when visiting a link that didn't work before to clear out/refresh any browser cache.

glhf!

**Comment by Marc13Bautista** [comment]
Thanks for the fix! And of course making this pregen.
